### ISSUE TITLE
Error using multimod push tags

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go-build-tools#177]
```bash
.tools/multimod verify && /Users/lazy/github/opentelemetry-go-build-tools/.tools/multimod tag -m tools -c HEAD -p -r upstream
Using versioning file /Users/lazy/github/opentelemetry-go-build-tools/versions.yaml
PASS: All modules exist in exactly one set.
PASS: All module versions are valid, and no module sets have same non-zero major version.
Finished checking all stable modules' dependencies.
PASS: Module sets successfully verified.
Using versioning file /Users/lazy/github/opentelemetry-go-build-tools/versions.yaml
Tagging commit 6207030c6369a5b3aaf54f68d125a81293a6d286:
v0.2.0
checkdoc/v0.2.0
chloggen/v0.2.0
crosslink/v0.2.0
dbotconf/v0.2.0
issuegenerator/v0.2.0
multimod/v0.2.0
semconvgen/v0.2.0
failed to pushTags tags: error pushing tag refs/tags/v0.2.0:authentication required
make: *** [push-tags] Error 1
```

**Comment by bryan-aguilar** [comment]
I'll need to take a deeper look into this. I had made the incorrect assumption that auth would be natively handled through the environment. It looks like the [example](https://github.com/go-git/go-git/blob/master/_examples/clone/auth/basic/access_token/main.go) explicitly setup auth by passing in a credential, in GitHubs case it would be a PAT.

**Comment by bryan-aguilar** [comment]
@bogdandrutu is providing a PAT in the environment on through a CLI Flag a reasonable solution? From initial investigation it appears that implementing some type of credential lookup in a platform agnostic way be me challenging. (see [here](https://github.com/src-d/go-git/issues/1101) for existing discussion that I found).

I was also thinking that another option could be to use something like `os.exec` to execute push commands [here](https://github.com/open-telemetry/opentelemetry-go-build-tools/blob/6207030c6369a5b3aaf54f68d125a81293a6d286/multimod/internal/tag/tag.go#L248) rather than the `go-git` library.

**Comment by bogdandrutu** [comment]
I think the CLI Flag/env or (CLI flag that fallback to env is good). Also os.exec may work, since I have my setup and when I run `git push upstream ${TAG}` works.

**Comment by bryan-aguilar** [comment]
Got it, I will make time to attempt a fix for the issue this week.

**Comment by bogdandrutu** [comment]
@bryan-aguilar another good option for us, is if we just print the tags, and let the makefile outside system deal with the push.

**Comment by bryan-aguilar** [comment]
That could definitely be done also. Are you leaning more toward a specific method? 
1. Provide a PAT
2. os.exec()
3. Printing tags

Sorry about the delay for this fix. I've gotten side tracked on some other work. If this is blocking a workflow and needs to be addressed quicker let me know.
